### PR TITLE
give ability to toggle waveforms on and off by left clicking on their legend

### PR DESCRIPTION
**Pull request by wfrgra**

### CODE REVIEW

**Comment by ma-laforge** [comment]
I allways wanted to add ability to disable waveforms myself.

...But I have to look at this a bit closer:
  - I question the DWaveform -> IWaveform modifications
  - plot.display_data -> plot.data modifications
  - ...

I also don't like the idea of using the legend to control line visibility:
  - I don't want NON-visible lines to show up in the legend.
  - I don't want to hide waveforms in the legend either (that will make it "impossible" to make them visible again).


I think I would prefer adding a special pop-up form to control line visiblility.
...I will look into this a bit further...

**Comment by wfrgra** [comment]
The DWaveform to IWaveform and plot.display_data to plot.data mods are there to ensure that the legend always prints the full list of possible waveforms, even those that are not visible. 
Having the legend display all waveforms is a bit untidy, but toggling the legend's symbol as well as the data gives a reasonable indication of which waveforms are currently displayed, while allowing the waveforms to be reenabled. 
I'm happy see the controls end up in a pop up instead, but this works for me for the time being.
Keep up the good work!

**Comment by ma-laforge** [comment]
I see:
DWaveform & display_data are post-processed datasets that are used for data reduction, etc. (basically to improve plotting speed).

The modifications cannot be done the way you propose because it will cause strange behaviours.

Feel free to keep using your version for the time being.  I will try to come up with a less disruptive PR (fewer side effects).  Just be aware that some behaviours might be off with your version (like slower plotting).

**Comment by ma-laforge** [comment]
@wfrgra : 

If you update to the newest version of InspectDR (0.3.4), you will now get a new dialog under the `Data|Traces` menu:

image

This solution now hides traces that are made non-visible from the legend - without loosing the ability to re-enable visibility.

It also does not bypass the speed enhancements provided by the `display_data/DWaveform` structures (not to mention the scaling issues that would have occured on non-linear axes).

**Comment by wfrgra** [comment]
Awesome! Thanks

**Comment by ma-laforge** [comment]
Feel free to open a new issue if something is not working.

**Pull request closed without merging**
